version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies
      - pip install -r requirements.txt


artifacts:
  files:
    - '**/*'